### ISSUE TITLE
Sometimes solvespace creates corrupt slvs files.

### ISSUE THREAD

**Issue by nekromant** [solvespace/solvespace#249]
### System information

This is SolveSpace version 2.3~.
(Latest deb-packaged version from releases)

Operating system: Debian Jessie (stable)
 
### Expected behavior

Solvespace should always save files correctly and load them. 

### Actual behavior

Sometimes, when saving complex designs solvespace produces a file it can't open afterwards. Opening such a corrupt file causes solvespace's window to stop responding and the solvespace process starts consuming 100% of CPU.  Removing some of the groups by hand from the slvs file sometimes helps out, but it's hard to guess which group is causing problems if there are many.  

### Additional information

For some reason github doesn't allow me to upload a zipped slvs, so here's a link to the corrupt slvs on my owncloud. 

https://cloud.ncrmnt.org/index.php/s/5qM4MDnD7suMwxs

**Comment by whitequark** [comment]
The file is definitely not corrupted. Both 2.3 and 3.0 can open the file, after a slight delay:
```
Generate::REGEN (for bounding box) took 50 ms
Generate::REGEN took 99 ms
Generate::ALL (for bounding box) took 416 ms
didn't converge
have 49.789 62.768 17.005
want 48.464 62.768 19.087
distance = 2.46811
Generate::ALL took 6478 ms
Generate::DIRTY (for bounding box) took 52 ms
Generate::DIRTY took 2387 ms
```
Is, perhaps, chord tolerance set to an unreasonably low value on your machine?

**Comment by nekromant** [comment]
@whitequark Hm, I think I figured it out. My Intel Sandybridge drivers were the issue. Since I'm using a dual-gfx laptop, running solvespace using the nvidia card solved the issue for me. 

Here's what I get from stdout from solvespace when trying to open the file on intel :
```
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 14: reading configurations from ~/.fonts.conf is deprecated. please move it to /home/necromant/.config/fontconfig/fonts.conf manually
Vector::WithMagnitude(1) of zero vector!
Vector::WithMagnitude(1) of zero vector!
Vector::WithMagnitude(1) of zero vector!
Vector::WithMagnitude(1) of zero vector!
Vector::WithMagnitude(1) of zero vector!
Vector::WithMagnitude(1) of zero vector!
Vector::WithMagnitude(1) of zero vector!
Vector::WithMagnitude(1) of zero vector!
The program 'solvespace' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 5291 error_code 8 request_code 72 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

And here's what I get from gdb when I ctrl+c it from the frozen state: 

```
Program received signal SIGINT, Interrupt.
0x00007ffff4b842cd in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
(gdb) bt
#0  0x00007ffff4b842cd in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007ffff4b68d6e in XGetGeometry () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff76fd045 in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#3  0x00007fffe36ec8f7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#4  0x00007fffe36eb712 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#5  0x00007fffe3631b2e in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#6  0x00007fffe3632d48 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#7  0x00007fffe36024d0 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#8  0x00007fffe3616af5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#9  0x00007fffe35eb076 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#10 0x00007fffe35d222c in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#11 0x00007fffe35e80b4 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#12 0x00007fffe34da933 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#13 0x00007fffe34daa18 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#14 0x00007fffe36328bb in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#15 0x00007fffe36eb41f in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#16 0x00007fffe36e8755 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#17 0x00007ffff76d5545 in glXMakeCurrentReadSGI () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#18 0x0000000000463325 in SolveSpace::TextWindowGtk::~TextWindowGtk() ()
#19 0x00007ffff3b14b29 in __run_exit_handlers (status=1, listp=0x7ffff3e825a8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#20 0x00007ffff3b14b75 in __GI_exit (status=<optimized out>) at exit.c:104
#21 0x00007ffff5c43001 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#22 0x00007ffff4b8645d in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#23 0x00007ffff4b833c7 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#24 0x00007ffff4b83485 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#25 0x00007ffff4b84430 in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#26 0x00007ffff4b68d6e in XGetGeometry () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#27 0x00007ffff76fd045 in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#28 0x00007fffe36ec8f7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#29 0x00007fffe36eb712 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#30 0x00007fffe3631b2e in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#31 0x00007fffe3632d48 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#32 0x00007fffe36024d0 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#33 0x00007fffe3616af5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
---Type <return> to continue, or q <return> to quit---
#34 0x00007fffe35eb076 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#35 0x00007fffe35cf7a7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#36 0x00007fffe35cfb96 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#37 0x00007fffe35d013e in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#38 0x00007fffe35d1739 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#39 0x00000000004ab055 in SolveSpace::SolveSpaceUI::GenerateAll(SolveSpace::SolveSpaceUI::GenerateType, bool, bool) ()
#40 0x00000000004eb986 in SolveSpace::SolveSpaceUI::AfterNewFile() ()
#41 0x00000000004ebb50 in SolveSpace::SolveSpaceUI::OpenFile(std::string const&) ()
#42 0x00000000004f1a3a in SolveSpace::SolveSpaceUI::MenuFile(int) ()
#43 0x00007ffff6c1baf0 in Gtk::MenuItem_Class::activate_callback(_GtkMenuItem*) () from /usr/lib/x86_64-linux-gnu/libgtkmm-2.4.so.1
#44 0x00007ffff4e94474 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff4eae087 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff4eae9df in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007ffff632eaf6 in gtk_widget_activate () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#48 0x00007ffff622a94d in gtk_menu_shell_activate_item () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#49 0x00007ffff622aceb in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#50 0x00007ffff6218a3f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#51 0x00007ffff4e94245 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#52 0x00007ffff4ea5e62 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#53 0x00007ffff4eae285 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#54 0x00007ffff4eae9df in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#55 0x00007ffff632fd6c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#56 0x00007ffff6217184 in gtk_propagate_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#57 0x00007ffff621761b in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#58 0x00007ffff5c3bb6c in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#59 0x00007ffff0259c5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#60 0x00007ffff0259f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#61 0x00007ffff025a272 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#62 0x00007ffff6216597 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#63 0x00007ffff6c19b82 in Gtk::Main::run(Gtk::Window&) () from /usr/lib/x86_64-linux-gnu/libgtkmm-2.4.so.1
#64 0x0000000000441598 in main ()
(gdb) 
(gdb) quit
A debugging session is active.
```

Here's the glxinfo for the intel card:
```
130 ✗ necromant @ sylwer ~ $ glxinfo 
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_multisample, GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_MESA_copy_sub_buffer, 
    GLX_OML_swap_method, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_make_current_read
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_import_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_MESA_copy_sub_buffer, GLX_MESA_multithread_makecurrent, 
    GLX_MESA_query_renderer, GLX_OML_swap_method, GLX_SGIS_multisample, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGI_make_current_read
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)
OpenGL version string: 3.0 Mesa 10.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
    GL_AMD_conservative_depth, GL_AMD_draw_buffers_blend, 
    GL_AMD_seamless_cubemap_per_texture, GL_AMD_shader_trinary_minmax, 
    GL_APPLE_packed_pixels, GL_APPLE_vertex_array_object, 
    GL_ARB_ES2_compatibility, GL_ARB_ES3_compatibility, 
    GL_ARB_blend_func_extended, GL_ARB_clear_buffer_object, 
    GL_ARB_color_buffer_float, GL_ARB_compressed_texture_pixel_storage, 
    GL_ARB_conditional_render_inverted, GL_ARB_conservative_depth, 
    GL_ARB_copy_buffer, GL_ARB_debug_output, GL_ARB_depth_buffer_float, 
    GL_ARB_depth_clamp, GL_ARB_depth_texture, GL_ARB_draw_buffers, 
    GL_ARB_draw_buffers_blend, GL_ARB_draw_elements_base_vertex, 
    GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location, 
    GL_ARB_explicit_uniform_location, GL_ARB_fragment_coord_conventions, 
    GL_ARB_fragment_program, GL_ARB_fragment_program_shadow, 
    GL_ARB_fragment_shader, GL_ARB_framebuffer_object, 
    GL_ARB_framebuffer_sRGB, GL_ARB_get_program_binary, 
    GL_ARB_half_float_pixel, GL_ARB_half_float_vertex, 
    GL_ARB_instanced_arrays, GL_ARB_internalformat_query, 
    GL_ARB_invalidate_subdata, GL_ARB_map_buffer_alignment, 
    GL_ARB_map_buffer_range, GL_ARB_multi_bind, GL_ARB_multisample, 
    GL_ARB_multitexture, GL_ARB_occlusion_query, GL_ARB_occlusion_query2, 
    GL_ARB_pixel_buffer_object, GL_ARB_point_parameters, GL_ARB_point_sprite, 
    GL_ARB_provoking_vertex, GL_ARB_robustness, GL_ARB_sampler_objects, 
    GL_ARB_seamless_cube_map, GL_ARB_seamless_cubemap_per_texture, 
    GL_ARB_separate_shader_objects, GL_ARB_shader_bit_encoding, 
    GL_ARB_shader_objects, GL_ARB_shader_texture_lod, 
    GL_ARB_shading_language_100, GL_ARB_shading_language_420pack, 
    GL_ARB_shading_language_packing, GL_ARB_shadow, GL_ARB_stencil_texturing, 
    GL_ARB_sync, GL_ARB_texture_border_clamp, GL_ARB_texture_compression, 
    GL_ARB_texture_compression_rgtc, GL_ARB_texture_cube_map, 
    GL_ARB_texture_env_add, GL_ARB_texture_env_combine, 
    GL_ARB_texture_env_crossbar, GL_ARB_texture_env_dot3, 
    GL_ARB_texture_float, GL_ARB_texture_mirror_clamp_to_edge, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_multisample, 
    GL_ARB_texture_non_power_of_two, GL_ARB_texture_query_levels, 
    GL_ARB_texture_rectangle, GL_ARB_texture_rg, GL_ARB_texture_rgb10_a2ui, 
    GL_ARB_texture_storage, GL_ARB_texture_storage_multisample, 
    GL_ARB_texture_swizzle, GL_ARB_timer_query, GL_ARB_transform_feedback2, 
    GL_ARB_transform_feedback3, GL_ARB_transform_feedback_instanced, 
    GL_ARB_transpose_matrix, GL_ARB_uniform_buffer_object, 
    GL_ARB_vertex_array_bgra, GL_ARB_vertex_array_object, 
    GL_ARB_vertex_attrib_binding, GL_ARB_vertex_buffer_object, 
    GL_ARB_vertex_program, GL_ARB_vertex_shader, 
    GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_vertex_type_2_10_10_10_rev, 
    GL_ARB_window_pos, GL_ATI_blend_equation_separate, GL_ATI_draw_buffers, 
    GL_ATI_separate_stencil, GL_ATI_texture_compression_3dc, 
    GL_ATI_texture_env_combine3, GL_ATI_texture_float, 
    GL_ATI_texture_mirror_once, GL_EXT_abgr, GL_EXT_bgra, GL_EXT_blend_color, 
    GL_EXT_blend_equation_separate, GL_EXT_blend_func_separate, 
    GL_EXT_blend_minmax, GL_EXT_blend_subtract, GL_EXT_compiled_vertex_array, 
    GL_EXT_copy_texture, GL_EXT_draw_buffers2, GL_EXT_draw_instanced, 
    GL_EXT_draw_range_elements, GL_EXT_fog_coord, GL_EXT_framebuffer_blit, 
    GL_EXT_framebuffer_multisample, GL_EXT_framebuffer_multisample_blit_scaled, 
    GL_EXT_framebuffer_object, GL_EXT_framebuffer_sRGB, 
    GL_EXT_gpu_program_parameters, GL_EXT_multi_draw_arrays, 
    GL_EXT_packed_depth_stencil, GL_EXT_packed_float, GL_EXT_packed_pixels, 
    GL_EXT_pixel_buffer_object, GL_EXT_point_parameters, 
    GL_EXT_polygon_offset, GL_EXT_provoking_vertex, GL_EXT_rescale_normal, 
    GL_EXT_secondary_color, GL_EXT_separate_specular_color, 
    GL_EXT_shader_integer_mix, GL_EXT_shadow_funcs, GL_EXT_stencil_two_side, 
    GL_EXT_stencil_wrap, GL_EXT_subtexture, GL_EXT_texture, GL_EXT_texture3D, 
    GL_EXT_texture_array, GL_EXT_texture_compression_latc, 
    GL_EXT_texture_compression_rgtc, GL_EXT_texture_cube_map, 
    GL_EXT_texture_edge_clamp, GL_EXT_texture_env_add, 
    GL_EXT_texture_env_combine, GL_EXT_texture_env_dot3, 
    GL_EXT_texture_integer, GL_EXT_texture_lod_bias, 
    GL_EXT_texture_mirror_clamp, GL_EXT_texture_object, 
    GL_EXT_texture_rectangle, GL_EXT_texture_sRGB, GL_EXT_texture_sRGB_decode, 
    GL_EXT_texture_shared_exponent, GL_EXT_texture_snorm, 
    GL_EXT_texture_swizzle, GL_EXT_timer_query, GL_EXT_transform_feedback, 
    GL_EXT_vertex_array, GL_EXT_vertex_array_bgra, 
    GL_IBM_multimode_draw_arrays, GL_IBM_rasterpos_clip, 
    GL_IBM_texture_mirrored_repeat, GL_INGR_blend_func_separate, GL_KHR_debug, 
    GL_MESA_pack_invert, GL_MESA_texture_signed_rgba, GL_MESA_window_pos, 
    GL_MESA_ycbcr_texture, GL_NV_blend_square, GL_NV_conditional_render, 
    GL_NV_depth_clamp, GL_NV_fog_distance, GL_NV_light_max_exponent, 
    GL_NV_packed_depth_stencil, GL_NV_primitive_restart, 
    GL_NV_texgen_reflection, GL_NV_texture_env_combine4, 
    GL_NV_texture_rectangle, GL_OES_EGL_image, GL_OES_read_format, 
    GL_SGIS_generate_mipmap, GL_SGIS_texture_border_clamp, 
    GL_SGIS_texture_edge_clamp, GL_SGIS_texture_lod, GL_SUN_multi_draw_arrays
``` 

Still not sure whether it's an intel drivers bug or a solvespace bug, so reporting everything here. Hope it helps.

**Comment by whitequark** [comment]
Neither. You aren't actually running SolveSpace on the Intel video card. You are using the Mesa/LLVMpipe software rasterizer (and I'd expect that to be noticeably slow, if not *unusably* slow).

See:

    OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)

And from the backtrace:

    #3  0x00007fffe36ec8f7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so

The Mesa software rasterizer is known to misbehave when used with SolveSpace, although I never figured out why. It is not considered a supported configuration.

**Comment by nekromant** [comment]
Okay, looks like we can close the issue for now. I'll have to tripple check my graphics settings, looks like I've got something terribly broken without me noticing.
